M27/MVC-BenutzerRollen/MVC-BenutzerRollen/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_BenutzerRollen.Models;

namespace MVC_BenutzerRollen.Controllers
{
    [Authorize]
    public class FilmController : Controller
    {
        private TeachSQLEntities2 db = new TeachSQLEntities2();

        // GET: Film
        [AllowAnonymous]
        public ActionResult Index()
        {
            var mOV_FILM = db.MOV_FILM.Include(m => m.MOV_PERSON);
            return View(mOV_FILM.OrderBy(x => -x.punkte).Take(10).ToList());
        }

        // GET: Film/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MOV_FILM mOV_FILM = db.MOV_FILM.Find(id);
            if (mOV_FILM == null)
            {
                return HttpNotFound();
            }
            return View(mOV_FILM);
        }

        // GET: Film/Create
        public ActionResult Create()
        {
            ViewBag.regie = new SelectList(db.MOV_PERSON, "id", "name");
            return View();
        }

        // POST: Film/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,titel,jahr,punkte,stimmen,regie")] MOV_FILM mOV_FILM)
        {
            if (ModelState.IsValid)
            {
                db.MOV_FILM.Add(mOV_FILM);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.regie = new SelectList(db.MOV_PERSON, "id", "name", mOV_FILM.regie);
            return View(mOV_FILM);
        }

        // GET: Film/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MOV_FILM mOV_FILM = db.MOV_FILM.Find(id);
            if (mOV_FILM == null)
            {
                return HttpNotFound();
            }
            ViewBag.regie = new SelectList(db.MOV_PERSON, "id", "name", mOV_FILM.regie);
            return View(mOV_FILM);
        }

        // POST: Film/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,titel,jahr,punkte,stimmen,regie")] MOV_FILM mOV_FILM)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mOV_FILM).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.regie = new SelectList(db.MOV_PERSON, "id", "name", mOV_FILM.regie);
            return View(mOV_FILM);
        }

        // GET: Film/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MOV_FILM mOV_FILM = db.MOV_FILM.Find(id);
            if (mOV_FILM == null)
            {
                return HttpNotFound();
            }
            return View(mOV_FILM);
        }

        // POST: Film/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MOV_FILM mOV_FILM = db.MOV_FILM.Find(id);
            db.MOV_FILM.Remove(mOV_FILM);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

M27/MVC-BenutzerRollen/MVC-BenutzerRollen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PeanutFilm</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PeanutFilm", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Filme", "Index", "Film", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PeanutFilm</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>